### ISSUE TITLE
Intermittent test failure for test_create_modify_and_delete_vis

### ISSUE THREAD

**Issue by jaypoulz** [isenseDev/rSENSE#2213]
**General description:** 
Stack Trace:
RenameVisTest

```
E  test_create_modify_and_delete_a_vis                            ERROR (8.18s)

Capybara::Webkit::NodeNotAttachedError:         Capybara::Webkit::NodeNotAttachedError: Element at 25 no longer present in the DOM

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-webkit-1.3.1/lib/capybara/webkit/browser.rb:275:in `check'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-webkit-1.3.1/lib/capybara/webkit/browser.rb:208:in `command'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-webkit-1.3.1/lib/capybara/webkit/node.rb:129:in `invoke'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-webkit-1.3.1/lib/capybara/webkit/node.rb:4:in `visible_text'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/element.rb:61:in `block in text'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/base.rb:80:in `synchronize'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/element.rb:57:in `text'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/document.rb:23:in `text'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/queries/text_query.rb:26:in `resolve_for'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:454:in `block in assert_text'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:453:in `assert_text'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:502:in `has_text?'

            /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'

            /home/travis/build/isenseDev/rSENSE/test/integration/rename_vis_test.rb:32:in `block in <class:RenameVisTest>'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-webkit-1.3.1/lib/capybara/webkit/browser.rb:275:in `check'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-webkit-1.3.1/lib/capybara/webkit/browser.rb:208:in `command'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-webkit-1.3.1/lib/capybara/webkit/node.rb:129:in `invoke'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-webkit-1.3.1/lib/capybara/webkit/node.rb:4:in `visible_text'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/element.rb:61:in `block in text'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/base.rb:80:in `synchronize'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/element.rb:57:in `text'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/document.rb:23:in `text'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/queries/text_query.rb:26:in `resolve_for'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:454:in `block in assert_text'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/base.rb:84:in `synchronize'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:453:in `assert_text'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/node/matchers.rb:502:in `has_text?'

        /home/travis/.rvm/gems/ruby-2.1.1/gems/capybara-2.4.4/lib/capybara/session.rb:676:in `block (2 levels) in <class:Session>'

        /home/travis/build/isenseDev/rSENSE/test/integration/rename_vis_test.rb:32:in `block in <class:RenameVisTest>'
```

**live/dev/localhost:** live
**iSENSE Version:** v7.2
**Logged in (Y or N):** N/A
**Admin (Y or N):** N/A

**OS:** Macintosh
**Browser/Version:** Firefox 38.0

**Steps to Reproduce:** 

9

**Comment by asalani93** [comment]
There's a couple others as well.  Most happen because Travis runs slow enough that sometimes the DOM isn't in the expected state, but it's not the kind of error that would trigger a wait.

**Comment by jaypoulz** [comment]
@asalani93 Would it be possible to have travis re-run failing tests a few times before declaring a broken build?

**Comment by asalani93** [comment]
[I found some stuff that might help with that.](http://stackoverflow.com/questions/9198614/re-run-failed-unit-tests-in-ruby)  I'll implement it with a couple of fixes to some of the tests that are failing.

@everyone: if a tests fails and re-running the test fixes it, put the name here and a line or two of the error.  I'm going to go through this eventually and fix them.

**Comment by doug-salvati** [comment]
Haven't had this issue in awhile... will reopen if it comes back up
